module.exports = {
  ADD_FEEDBACK: "ADD_FEEDBACK",
  ADD_VOTE: "ADD_VOTE",
  FEEDBACK_ADDED: "FEEDBACK_ADDED",
  INITIAL_STATE: "INITIAL_STATE",
  MAX_LENGTH: 100,
  MAX_USERNAME_LENGTH: 30,
  PING_INTERVAL: 30000,
  SET_USERNAME: "SET_USERNAME",
  VOTE_ADDED: "VOTE_ADDED"
};
